In [5]:
import sklearn
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris
#from sklearn.datasets import load_boston #<-- 사용금지
from sklearn.datasets import load_breast_cancer
from sklearn.datasets import load_diabetes
from sklearn.datasets import load_digits
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

iris = load_iris()
brc = load_breast_cancer()
dia = load_diabetes()
dig = load_digits()

iris_data = iris.data
iris_label = iris.target

#학습/테스트 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

#분류모델 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

#학습수행
dt_clf.fit(X_train, y_train)

#예측수행
pred = dt_clf.predict(X_test)

#학습결과 출력
print('\n예측 정확도 : {0: .4f}' .format(accuracy_score(y_test, pred)))

print('\n')
print(iris.data)
print(iris.data.shape)
print(iris.feature_names)
print(iris.target)
print(iris.target.shape)
print(iris.target_names)
print('----------------------')


'''
print(brc.data)
print(brc.feature_names)
print(brc.target)
print(brc.target_names)
print('----------------------')
print(dia.data)
print(dia.feature_names)
print(dia.target)
#print(dia.target_names) <-- 에러 발생. 원인 불명
print('----------------------')
print(dig.data)
print(dig.feature_names)
print(dig.target)
print(dig.target_names)
'''


예측 정확도 :  0.9333


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4

"\nprint(brc.data)\nprint(brc.feature_names)\nprint(brc.target)\nprint(brc.target_names)\nprint('----------------------')\nprint(dia.data)\nprint(dia.feature_names)\nprint(dia.target)\n#print(dia.target_names) <-- 에러 발생. 원인 불명\nprint('----------------------')\nprint(dig.data)\nprint(dig.feature_names)\nprint(dig.target)\nprint(dig.target_names)\n"