In [ ]:
import numpy as np

t_list = [[1, 2, 3],   ### list 형태는 코마(,)로 구분되고 옆으로 죽 나열된다.
          [4, 5, 6]]   
print(t_list, t_list.count)
t_arr = np.array(t_list)    ### array 는 코마없이 구조체로 표시된다.
print(t_arr)

arr1 = np.array([[1,2,3]])
print(arr1, '타입:', arr1.dtype, '디멘젼:',arr1.ndim, '차원:', arr1.shape)

arr2 = np.array([[1,2,3],
                [2,3,4]])
print(arr2, '타입:', arr2.dtype, '디멘젼:',arr2.ndim, '차원:', arr2.shape, '\n')

seq_arr = np.arange(10)
print('np.arange(10) ', seq_arr)

seq_arr2 = np.arange(start=0, stop=10)
print('np.arange(start=0, stop=10) 위와 똑같음 ', seq_arr2)

zero_arr = np.zeros((3,2), dtype='int32')
print('\nzero array ', zero_arr)

one_arr = np.ones((3,2), dtype='int32')
print('one array ', one_arr)

resh1 = seq_arr.reshape(2,5)
print('reshape 10 -> (2,5) ', resh1)

resh2 = seq_arr.reshape(5,2)
print('reshape 10 -> (5,2) ', resh2)

resh_a = resh1.reshape(5,2)
print('reshape (2,5) -> (5,2) ', resh_a)

resh1 = seq_arr.reshape(2,-1)
print('reshape 10 -> (2,-1) 즉 (2,5) ', resh1)

resh2 = seq_arr.reshape(5,-1)
print('reshape 10 -> (5,-1) 즉 (5,2) ', resh2)

arr3 = np.arange(8)
print('arr3 ', arr3)

arr3_1 = arr3.reshape(2,2,2)
print('arr3 -> (2,2,2) ', arr3_1)

arr3_2 = arr3.reshape(2,-1,1)
print('arr3 -> (2,-1,1) 즉 (2,4,1) ', arr3_2)

arr3_3 = arr3.reshape(-1,2,1)
print('arr3 -> (-1,2,1) 즉 (4,2,1) ', arr3_3)

arr3_t1 = arr3_1.reshape(-1,2,1)
print('arr (2,2,2) -> (-1,2,1) 즉 (4,2,1) ', arr3_t1)

arr3_t2 = arr3_2.reshape(-1,2,1)
print('arr (2,4,1) -> (-1,2,1) 즉 (4,2,1) ', arr3_t2)

'''특정위치 값 추출 (인덱싱)
'''

print('arr3 ', arr3)

val1 = arr3[2]
print('arr3[2] ', val1)

val2 = arr3[-1]
print('arr3[-1] 맨 뒤의 것 ', val2)

val3 = arr3[-2]
print('arr3[-2] 맨 뒤에서 2번째 것 ', val3)

'''연속 추출
'''
print('arr3[0:3] array의 0번째 부터 3-1번째까지 ', arr3[0:3])

'''2차원 array
'''
arr4 = np.arange(1, 10)
print('arr4 ', arr4)
arr4_rs1 = arr4.reshape(3,3)
print('arr4.reshape(3,3) \n', arr4_rs1)
print('arr4_rs1[1:3, 0:3]\n', arr4_rs1[1:3, 0:3])
print('arr4_rs1[:, 0:1]\n', arr4_rs1[:, 0:1])
print('arr4_rs1[:, 0]\n', arr4_rs1[:, 0])
print('arr4_rs1[0]\n', arr4_rs1[0])
print('arr4_rs1[0, :]\n', arr4_rs1[0, :])

'''팬시 인덱싱'''
print('arr4_rs1[[1,2], 2]  (** 팬시인덱싱 : 위 arr4_rs1[1:3, 2] 와 같다)\n', arr4_rs1[[1,2], 2])
print('arr4_rs1[[1,2], 0:3]  (** 팬시인덱싱 : 위 arr4_rs1[1:3, 0:3] 와 같다)\n', arr4_rs1[[1,2], 0:3])
print('arr4_rs1[[1,2]]      (** 팬시인덱싱 : 위 arr4_rs1[1:3, 0:3] 와 같다)\n', arr4_rs1[[1,2]])

'''불린 인덱싱'''
print('arr4_rs1[arr4_rs1 > 5] (** 불린인덱싱 : 5보다 큰 값만 표시)\n', arr4_rs1[arr4_rs1 > 5])
print('arr4_rs1 > 5 (** 5보다 큰 수식 결과 )\n', arr4_rs1 > 5)

'''정렬'''
print('\n---정렬')
arr5 = np.array([3,1,5,9])
print('arr5 ', arr5)
arr5_1 = np.sort(arr5)
print('np.sort(arr5) 및 arr5 ', arr5_1, arr5)
arr5.sort()
print('arr5.sort() 후 arr5 ', arr5)
arr5_1 = np.sort(arr5)[::-1]
print('np.sort(arr5)[::-1] 내림차순 arr5 정렬 ', arr5_1)

print('\n---정렬 n차원')
arr6 = np.array([[8,10],[11,7]])
print(arr6)
arr6_1 = np.sort(arr6, axis=0)
print('np.sort(arr6, axis=0) 열방향 정렬 \n', arr6_1)
arr6_1 = np.sort(arr6, axis=1)
print('np.sort(arr6, axis=1) 행방향 정렬 \n', arr6_1)

[[1, 2, 3], [4, 5, 6]] <built-in method count of list object at 0x0000021D1FA841C0>
[[1 2 3]
 [4 5 6]]
[[1 2 3]] 타입: int64 디멘젼: 2 차원: (1, 3)
[[1 2 3]
 [2 3 4]] 타입: int64 디멘젼: 2 차원: (2, 3) 

np.arange(10)  [0 1 2 3 4 5 6 7 8 9]
np.arange(start=0, stop=10) 위와 똑같음  [0 1 2 3 4 5 6 7 8 9]

zero array  [[0 0]
 [0 0]
 [0 0]]
one array  [[1 1]
 [1 1]
 [1 1]]
reshape 10 -> (2,5)  [[0 1 2 3 4]
 [5 6 7 8 9]]
reshape 10 -> (5,2)  [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
reshape (2,5) -> (5,2)  [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
reshape 10 -> (2,-1) 즉 (2,5)  [[0 1 2 3 4]
 [5 6 7 8 9]]
reshape 10 -> (5,-1) 즉 (5,2)  [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
arr3  [0 1 2 3 4 5 6 7]
arr3 -> (2,2,2)  [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
arr3 -> (2,-1,1) 즉 (2,4,1)  [[[0]
  [1]
  [2]
  [3]]

 [[4]
  [5]
  [6]
  [7]]]
arr3 -> (-1,2,1) 즉 (4,2,1)  [[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]

 [[6]
  [7]]]
arr (2,2,2) -> (-1,2,1) 즉 (4,2,1)  [[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]

 [[6]
  [7]]]
arr (2,4,1) -> (-1,2,1) 즉 (